import React, { useEffect, useMemo, useState } from 'react';
import http from '@/api/http';
import Spinner from '@/components/elements/Spinner';
import Button from '@/components/elements/Button';
import Input from '@/components/elements/Input';
import Integration from './components/Integration';
import ProjectSettings, { Project } from './components/ProjectSettingsV2';
import FileManager from './components/FileManagerV2';
import ClientLauncher from './components/ClientLauncher';
import CustomUpload from './components/CustomUpload';
import ModVersionAdder from './components/ModVersionAdder';
import ItemsPanel from './components/ItemsPanel';
import { Artwork, Callout, Card, EmptyState, Icon, IconName, Pagination, Pill, SectionHeading, StatCard, UI_STYLES, errorMessage } from './components/ui';
import { PTERODACTYL_STYLES } from './components/pterodactylStyles';
import { ServerContext } from '@/state/server';

type Section='Overview'|'Mods'|'Files'|'Custom uploads'|'Client launcher'|'Releases'|'Server integration'|'Settings';
type Provider='modrinth'|'curseforge';
type Hit={provider:Provider;projectId:string;title:string;author?:string;iconUrl?:string;description?:string;slug?:string};
type Revision={id:string;revision:number;pack_version:string;content_digest:string;changelog:string;actor?:string;created_at:string};
type Diff={added:any[];removed:any[];changed:any[]};
const RELEASE_PAGE_SIZE=8;
const nav:{name:Section;icon:IconName;description:string}[]=[
 {name:'Overview',icon:'overview',description:'Project status'}, {name:'Mods',icon:'mods',description:'Search and manage'},
 {name:'Files',icon:'files',description:'Managed file tree'}, {name:'Custom uploads',icon:'upload',description:'Trusted JARs'},
 {name:'Client launcher',icon:'package',description:'Player ZIP'}, {name:'Releases',icon:'releases',description:'Publish and rollback'},
 {name:'Server integration',icon:'server',description:'Startup sync'}, {name:'Settings',icon:'settings',description:'Project metadata'},
];
const normalize=(provider:Provider,raw:any):Hit=>provider==='modrinth'?{provider,projectId:String(raw.project_id||''),title:raw.title||raw.slug||'Untitled mod',author:raw.author,iconUrl:raw.icon_url,description:raw.description,slug:raw.slug}:{provider,projectId:String(raw.id||''),title:raw.name||raw.slug||'Untitled mod',author:raw.authors?.[0]?.name,iconUrl:raw.logo?.thumbnailUrl,description:raw.summary,slug:raw.slug};

export default function PackwizRouteV2(){
 const server=ServerContext.useStoreState(s=>s.server.data!); const base=`/api/client/extensions/packwizmanager/servers/${server.uuid}`;
 const[projects,setProjects]=useState<Project[]>([]),[active,setActive]=useState<Section>('Overview'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const[error,setError]=useState(''),[notice,setNotice]=useState(''),[refreshKey,setRefreshKey]=useState(0);
 const load=async()=>{setError('');try{const r=await http.get(`${base}/projects`);setProjects(r.data||[])}catch(e:any){setError(errorMessage(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[server.uuid]); const project=projects[0]; const current=useMemo(()=>nav.find(v=>v.name===active)!,[active]);
 const switchTo=(value:Section)=>{setActive(value);setError('');setNotice('')};
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');try{await http.post(`${base}/projects`,Object.fromEntries(new FormData(e.currentTarget)));setNotice('Project created.');await load()}catch(x:any){setError(errorMessage(x))}finally{setBusy(false)}};
 if(loading&&!projects.length)return <Spinner centered/>;
 if(!project)return <div className="pwm-root"><style>{UI_STYLES}{PTERODACTYL_STYLES}</style><div className="pwm-hero"><h1 className="pwm-title">Packwiz Manager</h1><p className="pwm-subtitle">Create a Packwiz project for {server.name}.</p></div>{error&&<Callout tone="error" icon="warning">{error}</Callout>}<Card><SectionHeading icon="plus" title="Create project" description="Set the Minecraft and loader versions for this server."/><form onSubmit={create} className="pwm-form-grid"><div className="pwm-field full"><label className="pwm-label">Pack name</label><Input name="display_name" required/></div><div className="pwm-field full"><label className="pwm-label">Slug</label><Input name="slug" pattern="[a-z0-9][a-z0-9-]{1,62}[a-z0-9]" required/></div><div className="pwm-field"><label className="pwm-label">Minecraft</label><Input name="minecraft_version" defaultValue="1.21.1" required/></div><div className="pwm-field"><label className="pwm-label">Pack version</label><Input name="pack_version" defaultValue="0.1.0" required/></div><div className="pwm-field"><label className="pwm-label">Loader</label><select className="pwm-select" name="loader" defaultValue="neoforge"><option>neoforge</option><option>fabric</option><option>forge</option><option>quilt</option></select></div><div className="pwm-field"><label className="pwm-label">Loader version</label><Input name="loader_version" required/></div><div className="full pwm-actions-right"><Button type="submit" disabled={busy}>Create project</Button></div></form></Card></div>;
 return <div className="pwm-root"><style>{UI_STYLES}{PTERODACTYL_STYLES}</style>
  <div className="pwm-hero"><div className="pwm-eyebrow"><Icon name="package" size={14}/> Packwiz · {server.name}</div><h1 className="pwm-title">{project.display_name}</h1><p className="pwm-subtitle">Manage the working pack and publish revisions used by the server and client launcher.</p><div className="pwm-hero-meta"><Pill>Minecraft {project.minecraft_version}</Pill><Pill>{project.loader} {project.loader_version}</Pill><Pill>Pack {project.pack_version}</Pill><Pill tone={project.current_revision?'good':'warn'}>{project.current_revision?'Published':'Draft'}</Pill></div></div>
  {error&&<div style={{marginBottom:12}}><Callout tone="error" icon="warning" title="Action failed">{error}</Callout></div>}{notice&&<div style={{marginBottom:12}}><Callout tone="good" icon="check">{notice}</Callout></div>}
  <div className="pwm-shell"><nav className="pwm-nav" aria-label="Packwiz sections">{nav.map(item=><button type="button" key={item.name} className={`pwm-nav-button ${active===item.name?'active':''}`} onClick={()=>switchTo(item.name)}><Icon name={item.icon} size={17}/><span><span className="pwm-nav-title">{item.name}</span><span className="pwm-nav-desc">{item.description}</span></span></button>)}</nav>
  <main className="pwm-main" aria-label={current.name}>
   {active==='Overview'&&<Overview project={project} open={switchTo}/>} 
   {active==='Mods'&&<Mods base={base} project={project} refreshKey={refreshKey} onChanged={m=>{setNotice(m);setRefreshKey(v=>v+1)}} onError={setError}/>} 
   {active==='Files'&&<Card><FileManager base={base} project={project.id} refreshKey={refreshKey} onChanged={m=>{setNotice(m);setRefreshKey(v=>v+1)}}/></Card>}
   {active==='Custom uploads'&&<CustomUpload base={base} project={project} refreshKey={refreshKey} onChanged={m=>{setNotice(m);setRefreshKey(v=>v+1)}} onError={setError}/>} 
   {active==='Client launcher'&&<ClientLauncher base={base} project={project} onOpenReleases={()=>switchTo('Releases')}/>} 
   {active==='Releases'&&<Releases base={base} project={project} reload={load} onNotice={setNotice} onError={setError}/>} 
   {active==='Server integration'&&<Integration base={base} project={project.id}/>} 
   {active==='Settings'&&<ProjectSettings base={base} project={project} reload={load}/>} 
  </main></div>
 </div>;
}

function Overview({project,open}:{project:Project;open:(s:Section)=>void}){return <div className="pwm-grid"><div className="pwm-grid pwm-grid-4"><StatCard icon="package" label="Minecraft" value={project.minecraft_version}/><StatCard icon="mods" label="Loader" value={project.loader}/><StatCard icon="releases" label="Pack" value={project.pack_version}/><StatCard icon="database" label="Status" value={project.current_revision?'Published':'Draft'}/></div><Card><SectionHeading icon="overview" title="Project workflow" description="Edit the working tree, publish a revision, then keep the server and clients synced to it."/><div className="pwm-grid pwm-grid-3">{([['Mods','Manage mods','Search providers and choose exact versions.'],['Files','Manage files','Browse configs and upload with drag and drop.'],['Releases','Publish revision','Create or roll back immutable snapshots.']] as [Section,string,string][]).map(([s,t,d])=><button type="button" className="pwm-result" key={s} onClick={()=>open(s)}><div><div className="pwm-result-title">{t}</div><div className="pwm-result-desc">{d}</div></div></button>)}</div></Card></div>}

function Mods({base,project,refreshKey,onChanged,onError}:{base:string;project:Project;refreshKey:number;onChanged:(m:string)=>void;onError:(m:string)=>void}){const[provider,setProvider]=useState<Provider>('modrinth'),[q,setQ]=useState(''),[hits,setHits]=useState<Hit[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[searching,setSearching]=useState(false);const search=async(p=1)=>{if(!q.trim())return;setSearching(true);try{const r=await http.get(`${base}/providers/${provider}/search`,{params:{q:q.trim(),minecraft:project.minecraft_version,loader:project.loader,page:p,page_size:12}});const d=Array.isArray(r.data)?{items:r.data,total:r.data.length,page:1}:r.data;setHits((d.items||[]).map((v:any)=>normalize(provider,v)));setTotal(d.total||0);setPage(d.page||p)}catch(e:any){onError(errorMessage(e))}finally{setSearching(false)}};return <div className="pwm-grid"><Card><SectionHeading icon="search" title="Add mods" description={`Search compatible ${project.loader} mods for Minecraft ${project.minecraft_version}.`}/><form className="pwm-toolbar" onSubmit={e=>{e.preventDefault();void search(1)}}><select className="pwm-select" value={provider} onChange={e=>setProvider(e.target.value as Provider)}><option value="modrinth">Modrinth</option><option value="curseforge">CurseForge</option></select><div className="pwm-field grow"><input className="pwm-select" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search mods"/></div><Button type="submit" disabled={searching}>{searching?'Searching…':'Search'}</Button></form>{hits.length>0&&<><div className="pwm-result-grid">{hits.map(hit=><div className="pwm-result" key={`${hit.provider}-${hit.projectId}`}><Artwork src={hit.iconUrl} name={hit.title} provider={hit.provider} size={44}/><div className="pwm-result-body"><div className="pwm-result-title">{hit.title}</div><div className="pwm-secondary">{hit.author||hit.provider}</div><div className="pwm-result-desc">{hit.description||'Compatible mod'}</div><ModVersionAdder base={base} projectId={project.id} minecraftVersion={project.minecraft_version} loader={project.loader} provider={hit.provider} providerProjectId={hit.projectId} displayName={hit.title} iconUrl={hit.iconUrl} author={hit.author} onAdded={onChanged} onError={onError}/></div></div>)}</div><Pagination page={page} total={total} pageSize={12} onPage={search} loading={searching}/></>}</Card><Card><ItemsPanel base={base} project={project.id} mode="mods" refreshKey={refreshKey}/></Card></div>}

function Releases({base,project,reload,onNotice,onError}:{base:string;project:Project;reload:()=>void;onNotice:(m:string)=>void;onError:(m:string)=>void}){
 const[rows,setRows]=useState<Revision[]>([]),[busy,setBusy]=useState(false),[notes,setNotes]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[diff,setDiff]=useState<Diff>();
 const[page,setPage]=useState(1),[comparing,setComparing]=useState(false);
 const load=async()=>{try{const r=await http.get(`${base}/projects/${project.id}/revisions`);const list:Revision[]=Array.isArray(r.data)?r.data:(r.data?.items||[]);setRows(list);setPage(current=>Math.min(current,Math.max(1,Math.ceil(list.length/RELEASE_PAGE_SIZE))));if(list.length>1&&!from&&!to){setFrom(String(list[1].revision));setTo(String(list[0].revision))}}catch(x:any){onError(errorMessage(x))}};
 useEffect(()=>{void load()},[project.id]);
 const publish=async()=>{setBusy(true);try{await http.post(`${base}/projects/${project.id}/publish`,{changelog:notes.trim()||'Published from Pterodactyl'});setNotes('');setPage(1);onNotice('Revision published.');await reload();await load()}catch(x:any){onError(errorMessage(x))}finally{setBusy(false)}};
 const rollback=async(n:number)=>{if(!confirm(`Switch to revision ${n}?`))return;setBusy(true);try{await http.post(`${base}/projects/${project.id}/rollback/${n}`);onNotice(`Revision ${n} is current.`);await reload();await load()}catch(x:any){onError(errorMessage(x))}finally{setBusy(false)}};
 const compare=async(nextFrom=from,nextTo=to)=>{if(!nextFrom||!nextTo||nextFrom===nextTo)return;setComparing(true);setFrom(nextFrom);setTo(nextTo);try{const r=await http.get(`${base}/projects/${project.id}/revisions/diff`,{params:{from:nextFrom,to:nextTo}});setDiff(r.data)}catch(x:any){onError(errorMessage(x))}finally{setComparing(false)}};
 const comparePrevious=(revision:Revision)=>{const index=rows.findIndex(row=>row.id===revision.id);const previous=index>=0?rows[index+1]:undefined;if(previous)void compare(String(previous.revision),String(revision.revision))};
 const visible=rows.slice((page-1)*RELEASE_PAGE_SIZE,page*RELEASE_PAGE_SIZE);
 const diffRows=diff?[...(diff.added||[]).map(v=>({...v,s:'Added'})),...(diff.changed||[]).map(v=>({...v,s:'Changed'})),...(diff.removed||[]).map(v=>({...v,s:'Removed'}))]:[];
 return <div className="pwm-grid">
  <Card><SectionHeading icon="releases" title="Publish revision" description="Snapshot the current working tree."/><label className="pwm-label">Release notes</label><textarea className="pwm-textarea" value={notes} onChange={e=>setNotes(e.target.value)}/><div className="pwm-actions-right" style={{marginTop:10}}><Button onClick={publish} disabled={busy}>Publish</Button></div></Card>
  <Card><SectionHeading icon="database" title="Release history" description="Newest revision first. Compare any revision directly with the release immediately before it." actions={<button className="pwm-icon-button" type="button" onClick={()=>void load()}><Icon name="refresh" size={14}/> Refresh</button>}/>
   {!rows.length?<EmptyState icon="releases" title="No revisions">Publish the first revision.</EmptyState>:<><div className="pwm-timeline">{visible.map(r=>{const index=rows.findIndex(row=>row.id===r.id);const previous=index>=0?rows[index+1]:undefined;return <div className="pwm-timeline-row" key={r.id}><div><Pill>Revision {r.revision}</Pill><div className="pwm-secondary">{new Date(r.created_at).toLocaleString()}</div></div><div><div className="pwm-name">Pack {r.pack_version}</div><div className="pwm-section-description">{r.changelog||'No notes'}</div><div className="pwm-code">{r.content_digest.slice(0,16)}…</div></div><div className="pwm-split-actions"><button className="pwm-icon-button" type="button" disabled={!previous||comparing} onClick={()=>comparePrevious(r)} title={previous?'Compare revision '+previous.revision+' with '+r.revision:'No previous revision'}><Icon name="code" size={14}/> Compare previous</button><Button isSecondary disabled={busy} onClick={()=>rollback(r.revision)}>Rollback</Button></div></div>})}</div><Pagination page={page} total={rows.length} pageSize={RELEASE_PAGE_SIZE} onPage={setPage}/></>}
  </Card>
  {rows.length>1&&<Card muted><SectionHeading icon="code" title="Compare revisions" description={from&&to?'Showing revision '+from+' → '+to+'. Choose another pair below or use Compare previous in release history.':'Inspect paths changed between snapshots.'}/><div className="pwm-toolbar"><select className="pwm-select" value={from} onChange={e=>setFrom(e.target.value)}>{rows.map(r=><option key={r.id} value={r.revision}>Revision {r.revision}</option>)}</select><select className="pwm-select" value={to} onChange={e=>setTo(e.target.value)}>{rows.map(r=><option key={r.id} value={r.revision}>Revision {r.revision}</option>)}</select><Button onClick={()=>void compare()} disabled={comparing||!from||!to||from===to}>{comparing?'Comparing…':'Compare'}</Button></div>{diff&&<>{diffRows.length?<><div className="pwm-progress" style={{marginBottom:10}}><Pill tone="good">{(diff.added||[]).length} added</Pill><Pill tone="blue">{(diff.changed||[]).length} changed</Pill><Pill>{(diff.removed||[]).length} removed</Pill></div><div className="pwm-table-wrap"><table className="pwm-table"><thead><tr><th>Status</th><th>Path</th></tr></thead><tbody>{diffRows.map((v:any,i)=><tr key={`${v.s}-${v.path}-${i}`}><td>{v.s}</td><td className="pwm-code">{v.path}</td></tr>)}</tbody></table></div></>:<Callout tone="good" icon="check">These revisions have no file changes.</Callout>}</>}</Card>}
 </div>;
}
