import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import http from '@/api/http';
import Button from '@/components/elements/Button';
import Input from '@/components/elements/Input';
import {Callout,Icon,Pill,SectionHeading,errorMessage} from './ui';

type Candidate={file:File;path:string};
type EntryHandle={isFile:boolean;isDirectory:boolean;name:string;file?:(ok:(f:File)=>void,fail?:(e:any)=>void)=>void;createReader?:()=>{readEntries:(ok:(e:EntryHandle[])=>void,fail?:(e:any)=>void)=>void}};
type TreeEntry={name:string;path:string;type:'directory'|'file';exists:boolean;children:number;size?:number;modified_at?:string;item_id?:string;kind?:string;provider?:string;side?:string;sha256?:string};
type TreeResponse={path:string;entries:TreeEntry[]};
type EditorState={path:string;filename:string;content:string;original:string};
const ROOTS=['config','defaultconfigs','kubejs','datapacks','resourcepacks'];
const clean=(s:string)=>s.replace(/\\/g,'/').replace(/^\/+/, '').split('/').filter(v=>v&&v!=='.').join('/');
const parent=(s:string)=>s.includes('/')?s.slice(0,s.lastIndexOf('/')):'';
const Folder=()=> <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 6h7l2 2h9v11H3z"/></svg>;
const FileIcon=()=> <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5"/></svg>;
const formatBytes=(size=0)=>size<1024?`${size} B`:size<1024*1024?`${(size/1024).toFixed(size<10240?1:0)} KB`:`${(size/1024/1024).toFixed(size<10*1024*1024?1:0)} MB`;
async function readAll(reader:ReturnType<NonNullable<EntryHandle['createReader']>>){const out:EntryHandle[]=[];for(;;){const batch=await new Promise<EntryHandle[]>((r,j)=>reader.readEntries(r,j));if(!batch.length)return out;out.push(...batch)}}
async function flatten(entry:EntryHandle,prefix=''):Promise<Candidate[]>{if(entry.isFile&&entry.file){const file=await new Promise<File>((r,j)=>entry.file!(r,j));return[{file,path:clean(prefix+file.name)}]}if(entry.isDirectory&&entry.createReader){const kids=await readAll(entry.createReader());return(await Promise.all(kids.map(k=>flatten(k,`${prefix}${entry.name}/`)))).flat()}return[]}
async function dropped(dt:DataTransfer){const entries=Array.from(dt.items||[]).map(i=>(i as any).webkitGetAsEntry?.()).filter(Boolean) as EntryHandle[];if(entries.length)return(await Promise.all(entries.map(e=>flatten(e)))).flat();return Array.from(dt.files||[]).map(file=>({file,path:file.name}))}

export default function FileManagerV2({base,project,refreshKey=0,onChanged}:{base:string;project:string;refreshKey?:number;onChanged?:(m:string)=>void}){
 const[entries,setEntries]=useState<TreeEntry[]>([]),[path,setPath]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[loading,setLoading]=useState(false),[working,setWorking]=useState(false),[drag,setDrag]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[showImport,setShowImport]=useState(false);
 const[editor,setEditor]=useState<EditorState|null>(null),[editorBusy,setEditorBusy]=useState(false),[downloading,setDownloading]=useState('');
 const filesInput=useRef<HTMLInputElement>(null),folderInput=useRef<HTMLInputElement>(null),dragDepth=useRef(0),requestSeq=useRef(0);
 const load=useCallback(async(target=path)=>{const seq=++requestSeq.current;setLoading(true);setError('');try{const r=await http.get(`${base}/projects/${project}/items`,{params:{view:'tree',path:target}});if(seq!==requestSeq.current)return;const data:TreeResponse=r.data||{path:target,entries:[]};setEntries(data.entries||[]);setSelected(old=>new Set([...old].filter(id=>(data.entries||[]).some(v=>v.item_id===id))))}catch(e:any){if(seq===requestSeq.current){setEntries([]);setError(errorMessage(e))}}finally{if(seq===requestSeq.current)setLoading(false)}},[base,project,path]);
 useEffect(()=>{setEntries([]);setSelected(new Set());setEditor(null);void load(path)},[path,refreshKey]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return entries.filter(v=>!q||(v.name+' '+v.path+' '+(v.kind||'')+' '+(v.provider||'')).toLowerCase().includes(q)).sort((a,b)=>a.type===b.type?a.name.localeCompare(b.name):a.type==='directory'?-1:1)},[entries,query]);
 const enter=(next:string)=>{if(next===path)return;requestSeq.current++;setEntries([]);setQuery('');setSelected(new Set());setEditor(null);setPath(next)};
 const upload=async(list:Candidate[])=>{if(!list.length)return;setWorking(true);setError('');setNotice('');let done=0;try{for(const c of list){const rel=clean(c.path||c.file.name);if(!rel||rel.split('/').includes('..'))throw new Error('Invalid upload path');const target=path?clean(`${path}/${rel}`):rel;if(!ROOTS.some(root=>target.startsWith(root+'/')))throw new Error(path?'Target is outside managed roots.':'Open a managed folder first, or drop a folder named config, defaultconfigs, kubejs, datapacks or resourcepacks.');const data=new FormData();data.append('file',c.file,c.file.name);data.append('target_path',target);await http.post(`${base}/projects/${project}/files`,data);done++}const m=`Uploaded ${done} ${done===1?'file':'files'}.`;setNotice(m);onChanged?.(m);await load(path)}catch(e:any){setError(errorMessage(e))}finally{setWorking(false)}};
 const fromInput=(list:FileList|null)=>{if(!list)return;const rows=Array.from(list).map(file=>({file,path:(file as any).webkitRelativePath||file.name}));void upload(rows)};
 const remove=async(rows:TreeEntry[])=>{const managed=rows.filter(v=>v.item_id);if(!managed.length||!confirm(`Remove ${managed.length} managed ${managed.length===1?'file':'files'}?`))return;setWorking(true);setError('');try{for(const row of managed)await http.delete(`${base}/projects/${project}/items/${row.item_id}`);setSelected(new Set());const m=`Removed ${managed.length} ${managed.length===1?'file':'files'}.`;setNotice(m);onChanged?.(m);await load(path)}catch(e:any){setError(errorMessage(e))}finally{setWorking(false)}};
 const importUrl=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setWorking(true);setError('');try{const form=e.currentTarget;await http.post(`${base}/projects/${project}/url-imports`,Object.fromEntries(new FormData(form)));form.reset();setShowImport(false);const m='Remote file imported.';setNotice(m);onChanged?.(m);await load(path)}catch(x:any){setError(errorMessage(x))}finally{setWorking(false)}};
 const openEditor=async(entry:TreeEntry)=>{setEditorBusy(true);setError('');setNotice('');try{const r=await http.get(`${base}/projects/${project}/items`,{params:{view:'content',path:entry.path}});const content=String(r.data?.content??'');setEditor({path:entry.path,filename:entry.name,content,original:content})}catch(e:any){setError(errorMessage(e))}finally{setEditorBusy(false)}};
 const saveEditor=async()=>{if(!editor)return;setEditorBusy(true);setError('');setNotice('');try{const data=new FormData();const blob=new Blob([editor.content],{type:'text/plain;charset=utf-8'});data.append('file',blob,editor.filename);data.append('target_path',editor.path);await http.post(`${base}/projects/${project}/files`,data);const m=`Saved ${editor.filename}.`;setEditor(current=>current?{...current,original:current.content}:current);setNotice(m);onChanged?.(m);await load(path)}catch(e:any){setError(errorMessage(e))}finally{setEditorBusy(false)}};
 const download=async(entry:TreeEntry)=>{setDownloading(entry.path);setError('');try{const r=await http.get(`${base}/projects/${project}/files/download`,{params:{path:entry.path},responseType:'blob'});const href=URL.createObjectURL(r.data);const anchor=document.createElement('a');anchor.href=href;anchor.download=entry.name;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(href),1000)}catch(e:any){setError(errorMessage(e))}finally{setDownloading('')}};
 const selectable=visible.filter(v=>v.type==='file'&&v.item_id);const selectedRows=entries.filter(v=>v.item_id&&selected.has(v.item_id));const allSelected=selectable.length>0&&selectable.every(v=>selected.has(v.item_id!));
 const selectAll=(yes:boolean)=>setSelected(old=>{const n=new Set(old);selectable.forEach(v=>yes?n.add(v.item_id!):n.delete(v.item_id!));return n});
 return <div className="pwm-file-manager"><SectionHeading icon="files" title="Files" description="Browse the actual managed project directories. Existing files can be downloaded, and text files up to 2 MB can be edited directly in the panel." actions={<span className="pwm-secondary">{path||'Managed roots'}</span>}/>
  {error&&<div style={{marginBottom:10}}><Callout tone="error" icon="warning">{error}</Callout></div>}{notice&&<div style={{marginBottom:10}}><Callout tone="good" icon="check">{notice}</Callout></div>}
  <div className="pwm-fm-toolbar"><div className="pwm-fm-breadcrumbs"><button className={!path?'active':''} onClick={()=>enter('')} type="button">Pack files</button>{path.split('/').filter(Boolean).map((part,i,parts)=>{const p=parts.slice(0,i+1).join('/');return <React.Fragment key={p}><span>/</span><button className={p===path?'active':''} onClick={()=>enter(p)} type="button">{part}</button></React.Fragment>})}</div><div className="pwm-fm-actions">{selectedRows.length>0&&<button className="pwm-icon-button pwm-danger" onClick={()=>void remove(selectedRows)} type="button"><Icon name="trash" size={14}/> Delete {selectedRows.length}</button>}<button className="pwm-icon-button" onClick={()=>setShowImport(v=>!v)} type="button"><Icon name="link" size={14}/> Import URL</button><Button type="button" disabled={working||!path} onClick={()=>filesInput.current?.click()}><span style={{display:'inline-flex',gap:6,alignItems:'center'}}><Icon name="upload" size={14}/> Upload files</span></Button><button className="pwm-icon-button" disabled={working||!path} onClick={()=>folderInput.current?.click()} type="button"><Folder/> Upload folder</button></div></div>
  <input ref={filesInput} type="file" multiple style={{display:'none'}} onChange={e=>fromInput(e.currentTarget.files)}/><input ref={folderInput} type="file" multiple style={{display:'none'}} {...({webkitdirectory:'',directory:''} as any)} onChange={e=>fromInput(e.currentTarget.files)}/>
  {showImport&&<form className="pwm-fm-import" onSubmit={importUrl}><div className="pwm-field pwm-fm-import-url"><label className="pwm-label">Source URL</label><Input name="url" type="url" required/></div><div className="pwm-field"><label className="pwm-label">Name</label><Input name="display_name" required/></div><div className="pwm-field"><label className="pwm-label">Target</label><Input name="target_path" defaultValue={path?`${path}/`:'config/'} required/></div><div className="pwm-field"><label className="pwm-label">Kind</label><select name="kind" className="pwm-select"><option value="config">Config</option><option value="kubejs">KubeJS</option><option value="datapack">Datapack</option><option value="resourcepack">Resource pack</option><option value="file">File</option></select></div><div className="pwm-field"><label className="pwm-label">Side</label><select name="side" className="pwm-select"><option value="both">Both</option><option value="server">Server</option><option value="client">Client</option></select></div><div className="pwm-fm-import-submit"><Button type="submit" disabled={working}>Import</Button></div></form>}
  <div className="pwm-fm-search-row"><div className="pwm-fm-search"><Icon name="search" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this folder…"/></div><button className="pwm-icon-button" onClick={()=>void load(path)} type="button" disabled={loading}><Icon name="refresh" size={14}/> Refresh</button></div>
  <div className={`pwm-fm-browser ${drag?'is-dragging':''}`} onDragEnter={e=>{e.preventDefault();dragDepth.current++;setDrag(true)}} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'}} onDragLeave={e=>{e.preventDefault();dragDepth.current=Math.max(0,dragDepth.current-1);if(!dragDepth.current)setDrag(false)}} onDrop={e=>{e.preventDefault();dragDepth.current=0;setDrag(false);void dropped(e.dataTransfer).then(upload).catch(x=>setError(errorMessage(x)))}}>
   {drag&&<div className="pwm-fm-drop-overlay"><Icon name="upload" size={24}/><strong>Drop to upload</strong><span>{path?`Upload into ${path}`:'Drop a managed root folder or open a folder first'}</span></div>}
   <table className="pwm-fm-table"><thead><tr><th className="pwm-fm-check"><input type="checkbox" checked={allSelected} onChange={e=>selectAll(e.target.checked)} disabled={!selectable.length}/></th><th>Name</th><th>Type</th><th>Size</th><th>Side</th><th>Integrity</th><th style={{minWidth:178,textAlign:'right'}}>Actions</th></tr></thead><tbody>
    {path&&!query&&<tr className="pwm-fm-row pwm-fm-folder-row"><td/><td><button className="pwm-fm-name-button" type="button" onClick={()=>enter(parent(path))}><span className="pwm-fm-glyph"><Folder/></span><span><strong>..</strong><small>Parent directory</small></span></button></td><td>Directory</td><td>—</td><td>—</td><td>—</td><td/></tr>}
    {visible.map(entry=>entry.type==='directory'?<tr key={entry.path} className="pwm-fm-row pwm-fm-folder-row"><td/><td><button className="pwm-fm-name-button" type="button" onClick={()=>enter(entry.path)}><span className="pwm-fm-glyph"><Folder/></span><span><strong>{entry.name}</strong><small>{entry.exists?`${entry.children} ${entry.children===1?'item':'items'}`:'Not created yet'}</small></span></button></td><td>Directory</td><td>—</td><td>—</td><td>—</td><td/></tr>:<tr key={entry.path} className={`pwm-fm-row ${entry.item_id&&selected.has(entry.item_id)?'is-selected':''}`}><td className="pwm-fm-check">{entry.item_id?<input type="checkbox" checked={selected.has(entry.item_id)} onChange={e=>setSelected(old=>{const n=new Set(old);e.target.checked?n.add(entry.item_id!):n.delete(entry.item_id!);return n})}/>:null}</td><td><div className="pwm-fm-name"><span className="pwm-fm-glyph"><FileIcon/></span><span><strong>{entry.name}</strong><small>{entry.provider==='filesystem'?'Existing project file · not tracked by Packwiz Manager':entry.provider==='url'?'Remote import':entry.provider||'Managed file'}</small></span></div></td><td><Pill tone={entry.provider==='url'?'blue':'default'}>{entry.kind||'file'}</Pill></td><td>{formatBytes(entry.size)}</td><td>{entry.side||'—'}</td><td>{entry.sha256?<span className="pwm-code" title={entry.sha256}>{entry.sha256.slice(0,12)}…</span>:entry.item_id?'—':<span className="pwm-secondary">Not tracked</span>}</td><td><div style={{display:'flex',justifyContent:'flex-end',gap:5,whiteSpace:'nowrap'}}><button className="pwm-icon-button" onClick={()=>void openEditor(entry)} type="button" disabled={editorBusy}>Edit</button><button className="pwm-icon-button" onClick={()=>void download(entry)} type="button" disabled={downloading===entry.path}>{downloading===entry.path?'Downloading…':'Download'}</button>{entry.item_id?<button className="pwm-fm-delete" onClick={()=>void remove([entry])} type="button" title="Remove managed file"><Icon name="trash" size={14}/></button>:null}</div></td></tr>)}
    {!loading&&!visible.length&&<tr><td colSpan={7}><div className="pwm-fm-empty"><Folder/><strong>{query?'No matching entries':'This directory is empty'}</strong><span>{query?'Try another search.':path?'Drop files here or use Upload files.':'Open a managed root folder.'}</span></div></td></tr>}
   </tbody></table>{loading&&<div className="pwm-fm-loading"><span/> Loading directory…</div>}
  </div>
  {editor&&<div style={{marginTop:12,border:'1px solid #374151',background:'#18212d',padding:14}}>
   <SectionHeading icon="code" title={`Edit ${editor.filename}`} description={editor.path} actions={<button className="pwm-icon-button" type="button" onClick={()=>setEditor(null)} disabled={editorBusy}>Close</button>}/>
   <textarea className="pwm-textarea" spellCheck={false} value={editor.content} onChange={e=>setEditor(current=>current?{...current,content:e.target.value}:current)} style={{minHeight:360,fontFamily:'ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace',fontSize:12,lineHeight:1.5,whiteSpace:'pre',overflow:'auto'}}/>
   <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,marginTop:10,flexWrap:'wrap'}}><span className="pwm-secondary">{new Blob([editor.content]).size.toLocaleString()} bytes{editor.content!==editor.original?' · Unsaved changes':' · Saved'}</span><div style={{display:'flex',gap:7}}><button className="pwm-icon-button" type="button" onClick={()=>setEditor(current=>current?{...current,content:current.original}:current)} disabled={editorBusy||editor.content===editor.original}>Reset</button><Button type="button" onClick={()=>void saveEditor()} disabled={editorBusy||editor.content===editor.original}>{editorBusy?'Saving…':'Save file'}</Button></div></div>
  </div>}
 </div>;
}
