import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import http from '@/api/http';
import Button from '@/components/elements/Button';
import Input from '@/components/elements/Input';
import {Callout,Icon,Pill,SectionHeading,errorMessage} from './ui';

type Item={id:string;kind:string;provider:string;display_name:string;target_path:string;filename:string;side:string;sha256?:string};
type Candidate={file:File;path:string};
type Entry={isFile:boolean;isDirectory:boolean;name:string;file?:(ok:(f:File)=>void,fail?:(e:any)=>void)=>void;createReader?:()=>{readEntries:(ok:(e:Entry[])=>void,fail?:(e:any)=>void)=>void}};
const ROOTS=['config','defaultconfigs','kubejs','datapacks','resourcepacks'];
const clean=(s:string)=>s.replace(/\\/g,'/').replace(/^\/+/, '').split('/').filter(v=>v&&v!=='.').join('/');
const parent=(s:string)=>s.includes('/')?s.slice(0,s.lastIndexOf('/')):'';
const Folder=()=> <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 6h7l2 2h9v11H3z"/></svg>;
const FileIcon=()=> <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5"/></svg>;
async function readAll(reader:ReturnType<NonNullable<Entry['createReader']>>){const out:Entry[]=[];for(;;){const batch=await new Promise<Entry[]>((r,j)=>reader.readEntries(r,j));if(!batch.length)return out;out.push(...batch)}}
async function flatten(entry:Entry,prefix=''):Promise<Candidate[]>{if(entry.isFile&&entry.file){const file=await new Promise<File>((r,j)=>entry.file!(r,j));return[{file,path:clean(prefix+file.name)}]}if(entry.isDirectory&&entry.createReader){const kids=await readAll(entry.createReader());return(await Promise.all(kids.map(k=>flatten(k,`${prefix}${entry.name}/`)))).flat()}return[]}
async function dropped(dt:DataTransfer){const entries=Array.from(dt.items||[]).map(i=>(i as any).webkitGetAsEntry?.()).filter(Boolean) as Entry[];if(entries.length)return(await Promise.all(entries.map(e=>flatten(e)))).flat();return Array.from(dt.files||[]).map(file=>({file,path:file.name}))}

export default function FileManagerV2({base,project,refreshKey=0,onChanged}:{base:string;project:string;refreshKey?:number;onChanged?:(m:string)=>void}){
 const[items,setItems]=useState<Item[]>([]),[path,setPath]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[loading,setLoading]=useState(false),[working,setWorking]=useState(false),[drag,setDrag]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[showImport,setShowImport]=useState(false);
 const filesInput=useRef<HTMLInputElement>(null),folderInput=useRef<HTMLInputElement>(null),dragDepth=useRef(0);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const first=await http.get(`${base}/projects/${project}/items`,{params:{group:'files',page:1,page_size:100,sort:'path',direction:'asc'}});const d=Array.isArray(first.data)?{items:first.data,total:first.data.length,page_size:100}:first.data;const all=[...(d.items||[])];const pages=Math.ceil((d.total||all.length)/Math.max(1,d.page_size||100));for(let p=2;p<=pages;p++){const r=await http.get(`${base}/projects/${project}/items`,{params:{group:'files',page:p,page_size:100,sort:'path',direction:'asc'}});all.push(...(r.data?.items||[]))}setItems(all);setSelected(old=>new Set([...old].filter(id=>all.some((v:Item)=>v.id===id))))}catch(e:any){setError(errorMessage(e))}finally{setLoading(false)}},[base,project]);
 useEffect(()=>{void load()},[load,refreshKey]);
 const folders=useMemo(()=>{if(query.trim())return[];if(!path)return ROOTS.map(name=>({name,path:name,count:items.filter(v=>v.target_path.startsWith(name+'/')).length}));const prefix=path+'/';const names=new Set<string>();items.forEach(v=>{if(v.target_path.startsWith(prefix)){const rest=v.target_path.slice(prefix.length),slash=rest.indexOf('/');if(slash>0)names.add(rest.slice(0,slash))}});return[...names].sort().map(name=>{const p=`${path}/${name}`;return{name,path:p,count:items.filter(v=>v.target_path.startsWith(p+'/')).length}})},[items,path,query]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(q)return items.filter(v=>(v.display_name+' '+v.target_path).toLowerCase().includes(q));if(!path)return[];const prefix=path+'/';return items.filter(v=>v.target_path.startsWith(prefix)&&!v.target_path.slice(prefix.length).includes('/'))},[items,path,query]);
 const enter=(p:string)=>{setPath(p);setQuery('');setSelected(new Set())};
 const upload=async(list:Candidate[])=>{if(!list.length)return;setWorking(true);setError('');setNotice('');let done=0;try{for(const c of list){const rel=clean(c.path||c.file.name);if(!rel||rel.split('/').includes('..'))throw new Error('Invalid upload path');const target=path?clean(`${path}/${rel}`):rel;if(!ROOTS.some(root=>target.startsWith(root+'/')))throw new Error(path?'Target is outside managed roots.':'Open a managed folder first, or drop a folder named config, defaultconfigs, kubejs, datapacks or resourcepacks.');const data=new FormData();data.append('file',c.file,c.file.name);data.append('target_path',target);await http.post(`${base}/projects/${project}/files`,data);done++}const m=`Uploaded ${done} ${done===1?'file':'files'}.`;setNotice(m);onChanged?.(m);await load()}catch(e:any){setError(errorMessage(e))}finally{setWorking(false)}};
 const fromInput=(list:FileList|null)=>{if(!list)return;const rows=Array.from(list).map(file=>({file,path:(file as any).webkitRelativePath||file.name}));void upload(rows)};
 const remove=async(rows:Item[])=>{if(!rows.length||!confirm(`Remove ${rows.length} managed ${rows.length===1?'file':'files'}?`))return;setWorking(true);setError('');try{for(const row of rows)await http.delete(`${base}/projects/${project}/items/${row.id}`);setSelected(new Set());const m=`Removed ${rows.length} ${rows.length===1?'file':'files'}.`;setNotice(m);onChanged?.(m);await load()}catch(e:any){setError(errorMessage(e))}finally{setWorking(false)}};
 const importUrl=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setWorking(true);setError('');try{const form=e.currentTarget;await http.post(`${base}/projects/${project}/url-imports`,Object.fromEntries(new FormData(form)));form.reset();setShowImport(false);const m='Remote file imported.';setNotice(m);onChanged?.(m);await load()}catch(x:any){setError(errorMessage(x))}finally{setWorking(false)}};
 const selectedRows=items.filter(v=>selected.has(v.id));const allSelected=visible.length>0&&visible.every(v=>selected.has(v.id));
 const selectAll=(yes:boolean)=>setSelected(old=>{const n=new Set(old);visible.forEach(v=>yes?n.add(v.id):n.delete(v.id));return n});
 return <div className="pwm-file-manager"><SectionHeading icon="files" title="Files" description="Browse the managed Packwiz file tree. Upload files and folders into the current directory, or drag them directly into the browser." actions={<span className="pwm-secondary">{items.length} managed files</span>}/>
  {error&&<div style={{marginBottom:10}}><Callout tone="error" icon="warning">{error}</Callout></div>}{notice&&<div style={{marginBottom:10}}><Callout tone="good" icon="check">{notice}</Callout></div>}
  <div className="pwm-fm-toolbar"><div className="pwm-fm-breadcrumbs"><button className={!path?'active':''} onClick={()=>enter('')} type="button">Pack files</button>{path.split('/').filter(Boolean).map((part,i,parts)=>{const p=parts.slice(0,i+1).join('/');return <React.Fragment key={p}><span>/</span><button className={p===path?'active':''} onClick={()=>enter(p)} type="button">{part}</button></React.Fragment>})}</div><div className="pwm-fm-actions">{selectedRows.length>0&&<button className="pwm-icon-button pwm-danger" onClick={()=>void remove(selectedRows)} type="button"><Icon name="trash" size={14}/> Delete {selectedRows.length}</button>}<button className="pwm-icon-button" onClick={()=>setShowImport(v=>!v)} type="button"><Icon name="link" size={14}/> Import URL</button><Button type="button" disabled={working||!path} onClick={()=>filesInput.current?.click()}><span style={{display:'inline-flex',gap:6,alignItems:'center'}}><Icon name="upload" size={14}/> Upload files</span></Button><button className="pwm-icon-button" disabled={working||!path} onClick={()=>folderInput.current?.click()} type="button"><Folder/> Upload folder</button></div></div>
  <input ref={filesInput} type="file" multiple style={{display:'none'}} onChange={e=>fromInput(e.currentTarget.files)}/><input ref={folderInput} type="file" multiple style={{display:'none'}} {...({webkitdirectory:'',directory:''} as any)} onChange={e=>fromInput(e.currentTarget.files)}/>
  {showImport&&<form className="pwm-fm-import" onSubmit={importUrl}><div className="pwm-field pwm-fm-import-url"><label className="pwm-label">Source URL</label><Input name="url" type="url" required/></div><div className="pwm-field"><label className="pwm-label">Name</label><Input name="display_name" required/></div><div className="pwm-field"><label className="pwm-label">Target</label><Input name="target_path" defaultValue={path?`${path}/`:'config/'} required/></div><div className="pwm-field"><label className="pwm-label">Kind</label><select name="kind" className="pwm-select"><option value="config">Config</option><option value="kubejs">KubeJS</option><option value="datapack">Datapack</option><option value="resourcepack">Resource pack</option><option value="file">File</option></select></div><div className="pwm-field"><label className="pwm-label">Side</label><select name="side" className="pwm-select"><option value="both">Both</option><option value="server">Server</option><option value="client">Client</option></select></div><div className="pwm-fm-import-submit"><Button type="submit" disabled={working}>Import</Button></div></form>}
  <div className="pwm-fm-search-row"><div className="pwm-fm-search"><Icon name="search" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search managed files…"/></div><button className="pwm-icon-button" onClick={()=>void load()} type="button"><Icon name="refresh" size={14}/> Refresh</button></div>
  <div className={`pwm-fm-browser ${drag?'is-dragging':''}`} onDragEnter={e=>{e.preventDefault();dragDepth.current++;setDrag(true)}} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'}} onDragLeave={e=>{e.preventDefault();dragDepth.current=Math.max(0,dragDepth.current-1);if(!dragDepth.current)setDrag(false)}} onDrop={e=>{e.preventDefault();dragDepth.current=0;setDrag(false);void dropped(e.dataTransfer).then(upload).catch(x=>setError(errorMessage(x)))}}>
   {drag&&<div className="pwm-fm-drop-overlay"><Icon name="upload" size={24}/><strong>Drop to upload</strong><span>{path?`Upload into ${path}`:'Drop a managed root folder or open a folder first'}</span></div>}
   <table className="pwm-fm-table"><thead><tr><th className="pwm-fm-check"><input type="checkbox" checked={allSelected} onChange={e=>selectAll(e.target.checked)}/></th><th>Name</th><th>Type</th><th>Side</th><th>Integrity</th><th/></tr></thead><tbody>
    {path&&!query&&<tr className="pwm-fm-row pwm-fm-folder-row"><td/><td><button className="pwm-fm-name-button" type="button" onClick={()=>enter(parent(path))}><span className="pwm-fm-glyph"><Folder/></span><span><strong>..</strong><small>Parent directory</small></span></button></td><td>Directory</td><td>—</td><td>—</td><td/></tr>}
    {folders.map(f=><tr key={f.path} className="pwm-fm-row pwm-fm-folder-row"><td/><td><button className="pwm-fm-name-button" type="button" onClick={()=>enter(f.path)}><span className="pwm-fm-glyph"><Folder/></span><span><strong>{f.name}</strong><small>{f.count} files</small></span></button></td><td>Directory</td><td>—</td><td>—</td><td/></tr>)}
    {visible.map(file=><tr key={file.id} className={`pwm-fm-row ${selected.has(file.id)?'is-selected':''}`}><td className="pwm-fm-check"><input type="checkbox" checked={selected.has(file.id)} onChange={e=>setSelected(old=>{const n=new Set(old);e.target.checked?n.add(file.id):n.delete(file.id);return n})}/></td><td><div className="pwm-fm-name"><span className="pwm-fm-glyph"><FileIcon/></span><span><strong>{file.filename||file.display_name}</strong><small>{query?file.target_path:file.display_name!==file.filename?file.display_name:file.provider==='url'?'Remote import':'Managed file'}</small></span></div></td><td><Pill tone={file.provider==='url'?'blue':'default'}>{file.provider==='url'?'URL import':file.kind}</Pill></td><td>{file.side}</td><td>{file.sha256?<span className="pwm-code" title={file.sha256}>{file.sha256.slice(0,12)}…</span>:'—'}</td><td><button className="pwm-fm-delete" onClick={()=>void remove([file])} type="button"><Icon name="trash" size={14}/></button></td></tr>)}
    {!loading&&!folders.length&&!visible.length&&<tr><td colSpan={6}><div className="pwm-fm-empty"><Folder/><strong>{query?'No matching files':'This directory is empty'}</strong><span>{query?'Try another search.':path?'Drop files here or use Upload files.':'Open a managed root folder.'}</span></div></td></tr>}
   </tbody></table>{loading&&<div className="pwm-fm-loading">Loading files…</div>}
  </div>
 </div>;
}
